import { PredefinedGift } from "./types";

export const PREDEFINED_GIFTS: PredefinedGift[] = [
  {
    id: "g1",
    name: "퐁신퐁신 구름 극세사 잠옷 세트",
    category: "fashion",
    genders: ["male", "female", "unisex"],
    ageGroups: ["10s", "20s", "30s"],
    budgetCategory: "30k_50k",
    vibes: ["healing", "practical", "emotional"],
    description: "보기만 해도 몸이 노곤노곤해지는 극강의 부드러움을 선사하는 극세사 수면잠옷입니다. 품이 넉넉해 누구나 편안히 잠에 빠져들 수 있어요.",
    price: "34,900원",
    tips: "겨울철 생일뿐만 아니라 따스한 이완이 필요한 친구에게 룸 스프레이와 함께 주면 지상낙원을 완성해요.",
    rating: 5,
  },
  {
    id: "g2",
    name: "조각달 도자기 티머그 & 캐모마일 블렌드 세트",
    category: "food",
    genders: ["female", "unisex"],
    ageGroups: ["20s", "30s", "40s", "50s", "60s+"],
    budgetCategory: "30k_50k",
    vibes: ["heating", "healing", "emotional"],
    description: "동글동글한 모카빛 도자기 머그와 티 필터, 향긋하게 정화해주는 오가닉 레몬 캐모마일 잎차 구성입니다.",
    price: "42,000원",
    tips: "머그 측면에 우드 스푼을 리본으로 묶어 선물하면 아기자기함이 두 배가 됩니다.",
    rating: 5,
  },
  {
    id: "g3",
    name: "은은한 모닥불 감성 우드쉘 오르골",
    category: "living",
    genders: ["female", "unisex"],
    ageGroups: ["10s", "20s"],
    budgetCategory: "50k_100k",
    vibes: ["emotional", "healing"],
    description: "태엽을 감으면 나무 심지가 조용히 타는 듯한 미세한 불빛과 함께 아날로그 빈티지 멜로디가 흘러나오는 원목 오르골 스탠드입니다.",
    price: "68,000원",
    tips: "소중한 사람의 탄생곡이나 지브리 멜로디 테마를 골라 선물 상자에 드라이플라워를 더해보세요.",
    rating: 5,
  },
  {
    id: "g4",
    name: "맥스 무선 저소음 목 마사지 베개",
    category: "healing",
    genders: ["male", "female", "unisex"],
    ageGroups: ["30s", "40s", "50s", "60s+"],
    budgetCategory: "50k_100k",
    vibes: ["practical", "healing"],
    description: "온열 패드가 내장되어 있어 온몸을 사르르 녹여주는 베개 타입 목-어깨 자동 지압 마사지기입니다.",
    price: "79,000원",
    tips: "일이 많아 고단한 직장인 친구나 부모님 기념일에 깜짝 안마 쿠폰 카드를 넣어 전달하세요.",
    rating: 4,
  },
  {
    id: "g5",
    name: "폭닥한 웜-터치 양면 보아 썸 핸드워머",
    category: "fashion",
    genders: ["male", "female", "unisex"],
    ageGroups: ["10s", "20s"],
    budgetCategory: "under_30k",
    vibes: ["practical", "funny"],
    description: "차가운 바람으로부터 손끝바닥을 도톰히 감싸주는 터치형 하이 테디 니트 장갑입니다. 엄지 손가락에 귀여운 스마일 패치가 포인트입니다.",
    price: "18,500원",
    tips: "가벼운 선물로 부담 없고, 귀여움을 좋아하는 친구에게 핫팩 파우치와 세트로 선물하세요.",
    rating: 5,
  },
  {
    id: "g6",
    name: "빈티지 레트로 블루투스 우드 스피커",
    category: "tech",
    genders: ["male", "unisex"],
    ageGroups: ["10s", "20s", "30s", "40s"],
    budgetCategory: "50k_100k",
    vibes: ["emotional", "practical", "luxurious"],
    description: "호두나무 원목으로 마감하여 고즈넉한 인테리어 소품 역할까지 완벽히 해내는 따스한 음색의 진공관 스타일 무선 스피커입니다.",
    price: "95,000원",
    tips: "선물하는 우드 스피커 뒤편에 친구 전용 음악 플레이리스트 QR코드를 인쇄해 붙여 보세요.",
    rating: 4,
  },
  {
    id: "g7",
    name: "핸드메이드 마블 소이 왁스 캔들워머 세트",
    category: "living",
    genders: ["female", "unisex"],
    ageGroups: ["20s", "30s"],
    budgetCategory: "30k_50k",
    vibes: ["emotional", "healing", "luxurious"],
    description: "대리석 원판과 미니멀한 골드 프레임의 조화가 세련된 워머와, 무화과 잎의 편안함을 가득 품은 천연 버터 미니 소이 캔들입니다.",
    price: "47,000원",
    tips: "방 안 분위기가 순식간에 고급 호텔처럼 변하는 마법을 느낄 수 있어요.",
    rating: 4,
  },
  {
    id: "g8",
    name: "허니 골드 오가닉 핸드 보습 밤 세트",
    category: "beauty",
    genders: ["male", "female", "unisex"],
    ageGroups: ["10s", "20s", "30s", "40s", "50s", "60s+"],
    budgetCategory: "under_30k",
    vibes: ["practical", "healing"],
    description: "식물성 시어버터와 허니 성분이 가득 들어가 거칠고 트기 쉬운 손을 실크처럼 촉촉하게 가꿔주는 무자극 보습 시그니처 듀오입니다.",
    price: "24,000원",
    tips: "건조한 직장에서 고군분투하는 동료에게 살며시 건네기 최적의 아이템입니다.",
    rating: 5,
  },
  {
    id: "g9",
    name: "수제 수플레 마카롱 & 휘낭시에 구움과자 박스",
    category: "food",
    genders: ["male", "female", "unisex"],
    ageGroups: ["10s", "20s", "30s"],
    budgetCategory: "under_30k",
    vibes: ["funny", "emotional", "practical"],
    description: "유기농 밀가루와 프랑스 고메 버터로 매일 아침 구워 더없이 고소한 다과 선물 상자입니다. 겉바속촉 휘낭시에 6종 세트.",
    price: "22,000원",
    tips: "커피나 밀크티를 즐겨 마시는 단것 러버 친구에게 이 상자를 전해 달콤함을 안겨주세요.",
    rating: 4,
  },
  {
    id: "g10",
    name: "무선 스마트 LED 에센셜 아로마 가습기",
    category: "tech",
    genders: ["female", "unisex"],
    ageGroups: ["20s", "30s", "40s"],
    budgetCategory: "30k_50k",
    vibes: ["practical", "healing"],
    description: "포근한 캔들 불빛 모양 LED 필터와 오일 디퓨저 기능이 접목된 무선 무소음 대용량 탁상용 가습기입니다.",
    price: "38,500원",
    tips: "독서나 야근할 때 은은한 보습과 광원으로 안락함을 전달할 수 있습니다.",
    rating: 5,
  },
  {
    id: "g11",
    name: "정밀 자세 교정 메모리폼 안식 방석",
    category: "healing",
    genders: ["male", "female", "unisex"],
    ageGroups: ["20s", "30s", "40s", "50s", "60s+"],
    budgetCategory: "30k_50k",
    vibes: ["practical"],
    description: "의자에 오래 앉아 일하거나 공부하는 부위에 걸리는 압력을 고르게 분산시켜 척추 압박을 최소화해주는 프리미엄 방석입니다.",
    price: "36,000원",
    tips: "유대감 깊은 수험생, 논문 쓰는 동기, 사무실 짝꿍에게 적극 추천하는 생존 꿀템입니다.",
    rating: 4,
  },
  {
    id: "g12",
    name: "프리미엄 1등급 한우 모둠 스팀 홈파티 키트",
    category: "food",
    genders: ["male", "female", "unisex"],
    ageGroups: ["30s", "40s", "50s", "60s+"],
    budgetCategory: "over_200k",
    vibes: ["luxurious", "practical"],
    description: "마블링이 촘촘한 특상 한우 꽃등심, 안심, 갈비 부위와 풍성한 가니쉬 채소가 올가닉 스팀 전용 보랭 쿠킹 박스에 담겨 발송됩니다.",
    price: "249,000원",
    tips: "격식을 차려야 하는 상사나 소중한 효도 안방 파티용 부모님 생일 선물로 탁월합니다.",
    rating: 5,
  },
  {
    id: "g13",
    name: "빈티지 리넨 실 다이어리 & 가죽 만년필 세트",
    category: "hobby",
    genders: ["male", "female", "unisex"],
    ageGroups: ["20s", "30s", "40s"],
    budgetCategory: "50k_100k",
    vibes: ["emotional", "luxurious"],
    description: "고급 이탈리아 가죽을 덧댄 황동 배럴 만년필과 실로 꼼꼼히 꿰매어 완벽한 180도 펼침을 보이는 올가닉 리넨 양장 노트 세트입니다.",
    price: "72,000원",
    tips: "노트 첫 페이지에 축하 필사 글귀나 정성 가득한 편지를 적어두면 깊은 여운을 전합니다.",
    rating: 5,
  },
  {
    id: "g14",
    name: "폭신 구름 수제 버그 퀼팅 요가매트",
    category: "hobby",
    genders: ["female", "unisex"],
    ageGroups: ["20s", "30s", "40s"],
    budgetCategory: "50k_100k",
    vibes: ["practical", "healing"],
    description: "친환경 천연 고무 레이어에 폭닥한 보아 퀼팅 면 커버가 덧씌워져, 홈트나 스트레칭을 할 때 포근한 매트에서 쉬는 감각을 제공합니다.",
    price: "85,000원",
    tips: "요가 명상 음악 앨범 테마 카드와 감성 매트 스트랩과 함께 기프트해 보세요.",
    rating: 4,
  }
];

export const COZY_MASCOT_QUOTES = [
  "안녕! 나는 선물을 찾아다니는 구름 강아지 '포구'야. 폭닥폭닥한 하루를 만드는 선물을 찾아줄게! 🐶🌸",
  "소중한 그 사람의 취향을 세세히 알려주면, 내가 가슴 따뜻해지는 맞춤 선물을 콕 골라줄 수 있구!",
  "친구의 생일을 캘린더에 연동해 두면, 내가 잊지 않게 미리 콩콩 알려줄게! 걱정 마구!",
  "추천 선물의 포근지수가 하트 가득하다면, 주는 마음도 받는 마음도 더없이 특별해질 거구! 💝",
  "어떤 조건이든 좋아! 너무 비싸지 않아도 마음을 듬뿍 채울 수 있는 아기자기한 선물들이 있단 사실을 기억해구!"
];
